# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0763609e36630e86aaa0d3be80aa0c89789317bde0d30490706c7ef384dea569fa955c4eaa16037c34130ba8517386c022689e919230a9d77382ffac3e8c7eba

test:
  secret_key_base: 60f9d3d132d8ae77fed072a0b7fd3d3e978ea8a73b33dbdfdfa5300eba94ce6418615392f710aff13cf3a4d21bcba0c0458220d4868df8a5e8a8c9f4bbd0d89d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
