# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0380e1ae9dfec3cd7f58dbb2fc998afa17122fa97f9eaa47057b1f484e8ac0c993a1e41b37a1c6f5b3552ab7ae397adb402aeed81fca4b633944652f584c6e26

test:
  secret_key_base: 388c8c65459cf434ccb7a7f2f445eeead05cd206c8edc0f3b434bf77ad24c5e370f96a128b83e99d7668d7939575e3b764d823760f3d5f3605981b092f64e9fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
