# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34947af761190e3867a1be7fcaea203fcc1258c035d17cc656e2dde8359f04008b9936e698f75bf001622708366f1ff165b4afbfed626af98bbb33e5a87d8617

test:
  secret_key_base: 711b0d2de41461dd44e74254cafc58db3dbd543956545b01753bec268f53f34f733442d032a3c811fdd0a997be9bac9ac6956d57dac08d0e7557dfd56e48fc2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
