# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc3ee5805a139a6e7eb3fafcc1b8a567fe3e208619354ca55432016df065d3c34a56390471dce7fdad69480d63895c9cc9a1a88aee861ce443af98ca78e9aa99

test:
  secret_key_base: 4291a33303df53720ba40fd25e2a95a2da5ea37817cfdcb8d0b73531cde15ae81f7c062f362674274fcc1459177c0fc8fcf3eddce27d9faa03f775ffec2964db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
