# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14440b3a2f4ee0bf5badd76ffb72b3494f244ba5f3736b0048a48b7448173ba7c0d42f1b763a3644d3052325a42e2854926af211aa569a6faa79db0cdba75a8b

test:
  secret_key_base: 4df69225bc4f234f64be443ff7913a2c0a1bf001c0598185bc8fe45a32fef204f85011da774c6c69d831b03e97ae7d4c04f755c836f12a8833508bd862ab6d02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
